apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-e-ingress
spec:
  ingressClassName: caddy
  rules:
  - host: mongo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mongo-express
            port:
              number: 80